apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grgconseils-certificate
spec:
  dnsNames:
    - grgconseils.ca
    - www.grgconseils.ca
  secretName: grgconseils-tls
  issuerRef:
    name: grgconseils-letsencrypt-prod
    kind: ClusterIssuer
